name: CI/CD Security Pipeline

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Static code scan (Semgrep)
        uses: returntocorp/semgrep-action@v1
        with:
          config: "auto"

      - name: Build Docker image
        run: docker build -t secure-microservice:latest .

      - name: Trivy container scan
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: secure-microservice:latest
          format: table
          exit-code: 1
          severity: CRITICAL,HIGH

      - name: Push to DockerHub (only if above passes)
        if: success()
        run: |
          echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
          docker tag secure-microservice yourusername/secure-microservice:latest
          docker push yourusername/secure-microservice:latest
